AWSTemplateFormatVersion: 2010-09-09

Description: | 
  CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2 AMI
  (latest ami) EC2 Instance with custom security group
  allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github
  repository, then installed on Flask.

Parameters:
  MyKey:
    Description: 
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Metadata:
  
Mappings:
  
Conditions:
  
Resources:
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables HTTP&SSH # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22 
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: !Ref MyKey
      SecurityGroupIds: 
        - !Ref MySG
      SecurityGroups: 
        SecurityGroups
      Tags: 
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install python3
        pip3 install
        cd /home/ec2-user
        FOLDER = "buraya github raw linki gelecek"
        wget ${FOLDER}/app.py
        mkdir templates && cd templates
        wget ${FOLDER}/index.html
        wget ${FOLDER}/result.html
        

Outputs: